# Jekyll Development Container
FROM mcr.microsoft.com/devcontainers/ruby:3.2

# Install Jekyll and Bundler
RUN gem install jekyll bundler

# Change the working directory to the Rockhubfestival subfolder
WORKDIR /workspace/Rockhubfestival